---
# vars file for baseline
baseline_packages:
  - nfs-common
  - nfs-server
  - dphys-swapfile
  - vim
  - ntp
  - heartbeat
  - haproxy

ip:
  - master1: 192.168.86.164
    master2: 192.168.86.163
    worker1: 192.168.86.160
    worker2: 192.168.86.158
    worker3: 192.168.86.159
    lb1: 192.168.86.161
    lb2: 192.168.86.162
    kubernetes: 192.168.86.100
    lb_heartbeat: 192.168.86.100
    worker_heartbeat: 192.168.86.101
