---
# tasks file for baseline
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  tags: update

- name: Install Packages
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ baseline_packages }}"

- name: Disable Swap_1
  become: true
  command: dphys-swapfile swapoff

- name: Disable Swap_2
  become: true
  command: dphys-swapfile uninstall

- name: Disable Swap_3
  become: true
  command: systemctl disable dphys-swapfile

- name: Set Authorized Keys
  authorized_key:
    user: pirate
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Copy Cloud Host File
  become: yes
  template:
    src: templates/hosts.debian.tmpl
    dest: /etc/cloud/templates/hosts.debian.tmpl
    owner: root
    group: root
    mode: '0644'

# reboot if changed
- name: Set Hostnames
  become: true
  hostname: name={{ inventory_hostname }}
  notify: Reboot
