- name: Current Kubeadm Check
  stat:
    path: $HOME/.kube/config
  register: kube_config

- fail:
    msg: Ending this playbook. Kubeadm Init already completed
  when: kube_config.stat.exists == True

- name: Copy kubeadm-config.yaml
  template:
    src: ../templates/masters/kubeadm-config.yaml
    dest: /home/pirate/kubeadm-config.yaml
  with_items: "{{ ip }}"

- name: Kubeadm init Master1
  become: yes
  command: kubeadm init --config /home/pirate/kubeadm-config.yaml --upload-certs
  tags: kubeadm_init

- name: Create a directory if it does not exist
  file:
    path: $HOME/.kube
    state: directory
    mode: '0755'
  tags: kubeadm_config

- name: Copy config file
  become: yes
  command: cp /etc/kubernetes/admin.conf /home/pirate/.kube/config
  tags: kubeadm_config

- name: Chown file
  become: true
  file:
    path: /home/pirate/.kube/config
    owner: pirate
    group: pirate
  tags: kubeadm_config

- name: Copy Weave Network Manifest
  template:
    src: ../templates/masters/weave.sh
    dest: $HOME/weave.sh
  tags: kubectl_network_manifest

- name: Apply Weave Network Manifest
  command: bash $HOME/weave.sh
  tags: kubectl_apply_weave

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  tags: kubeadm_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="../templates/workers/join-command.sh"
  tags: kubeadm_command
